version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image..
      - docker docker pull grafana/k6
  build:
    commands:
      - echo Run Peak test
      - docker run -i grafana/k6 run - <test.js
  post_build:
    commands:
      - echo Peak test complete
